function history = get_HistoryInit()
%GET_HISTORYINIT Initialize grouped history logs.

history = struct();

history.pred = struct( ...
    'pre', struct([]), ...
    'opt', struct([]));

history.app = get_step_hist();
history.base = get_base_hist();

history.meta = struct( ...
    'base_batt', [], ...
    'base_v_prev', NaN, ...
    'base_dist', NaN, ...
    'app_v_prev', NaN, ...
    'app_dist', NaN, ...
    'pos0', NaN);

end

function S = get_step_hist()
S = struct( ...
    'v', [], ...
    'lane', [], ...
    'step', [], ...
    't', [], ...
    'pos', [], ...
    'spd', [], ...
    'acc', [], ...
    'P_req', [], ...
    'P_trac', [], ...
    'P_cool', [], ...
    'P_heat', [], ...
    'P_tms', [], ...
    'Q_batt', [], ...
    'I_batt', [], ...
    'Q_Ah', [], ...
    'SOC', [], ...
    'trq', [], ...
    'rpm', [], ...
    'Ah_ir', [], ...
    'Rin', [], ...
    'Q_loss', [], ...
    'AgeCost', [], ...
    'T_batt', [], ...
    'T_ref', [], ...
    'Q_env', [], ...
    'Q_cool', [], ...
    'Q_heat', [], ...
    'f_dist', [], ...
    'r_dist', [], ...
    'f_v', [], ...
    'r_v', [], ...
    'link', [], ...
    'laneidx', [], ...
    'v_lb', [], ...
    'v_ub', [], ...
    'a_lb', [], ...
    'a_ub', []);
end

function S = get_base_hist()
S = struct( ...
    'v', [], ...
    'acc', [], ...
    'pos_rel', [], ...
    'pos', [], ...
    'P_req', [], ...
    'P_trac', [], ...
    'P_cool', [], ...
    'P_heat', [], ...
    'P_tms', [], ...
    'Q_batt', [], ...
    'I_batt', [], ...
    'Q_Ah', [], ...
    'SOC', [], ...
    'trq', [], ...
    'rpm', [], ...
    'Ah_ir', [], ...
    'Rin', [], ...
    'Q_loss', [], ...
    'AgeCost', [], ...
    'T_batt', [], ...
    'T_ref', [], ...
    'Q_env', [], ...
    'Q_cool', [], ...
    'Q_heat', []);
end
