function fields = get_pred_hist()
%GET_PRED_HIST Canonical EV output fields shared across prediction logs.

fields = {'P_req','I_batt','Q_Ah','SOC', ...
          'trq','rpm','Q_batt','Ah_ir','Rin','Q_loss','AgeCost','grade', ...
          'T_batt','T_ref','P_cool','P_heat','P_tms', ...
          'Q_env','Q_cool','Q_heat'};
end
