function history = get_appd_hist(history, group, ev)
%GET_APPD_HIST Append one EV sample to history.app or history.base.

map = {'P_req',  'P_req'; ...
       'P_trac', 'P_trac'; ...
       'P_cool', 'P_cool'; ...
       'P_heat', 'P_heat'; ...
       'P_tms',  'P_tms'; ...
       'Q_batt', 'Q_batt'; ...
       'I_batt', 'I_batt'; ...
       'Q_Ah',   'Q_Ah'; ...
       'SOC',    'SOC'; ...
       'trq',    'trq'; ...
       'rpm',    'rpm'; ...
       'Ah_ir',  'Ah_ir'; ...
       'Rin',    'Rin'; ...
       'Q_loss', 'Q_loss'; ...
       'AgeCost','AgeCost'; ...
       'T_batt', 'T_batt'; ...
       'T_ref',  'T_ref'; ...
       'Q_env',  'Q_env'; ...
       'Q_cool', 'Q_cool'; ...
       'Q_heat', 'Q_heat'};

if ~isfield(history, group) || ~isstruct(history.(group))
    error('get_appd_hist:InvalidGroup', 'history.%s is missing.', group);
end

for i = 1:size(map,1)
    name = map{i,1};
    ev_name = map{i,2};

    if ~isfield(history.(group), name) || isempty(history.(group).(name))
        history.(group).(name) = [];
    end

    history.(group).(name)(end+1,1) = getfield_safe(ev, ev_name, NaN);
end
end

function v = getfield_safe(S, name, default)
v = default;
if isstruct(S) && isfield(S,name) && ~isempty(S.(name))
    v = S.(name);
end
end
